// C Program to design a shell in Linux
#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<unistd.h>
#include<sys/types.h>
#include<sys/wait.h>
#include<readline/readline.h>
#include<readline/history.h>
#include<dirent.h>
#include<sys/stat.h>
#include<time.h>
#define MAXCOM 100000 // max number of letters to be supported
#define MAXLIST 100000 // max number of commands to be supported

// Clearing the shell using escape sequences
#define clear() printf("\033[H\033[J")

// Greeting shell during startup
void init_shell()
{
    clear();
    printf("\n\n\n\n******************"
        "************************");
    printf("\n\n\n\t****MY SHELL****");
    printf("\n\n\t-USE AT YOUR OWN RISK-");
    printf("\n\n\n\n*******************"
        "***********************");
    char* username = getenv("USER");
    printf("\n\n\nUSER is: @%s", username);
    printf("\n");
    sleep(1);
    clear();
}
int isLinuxCommand(char* cmd) {
    // Construct the command string to check if the command exists using `which`
    char command[100];
    snprintf(command, sizeof(command), "which %s > /dev/null 2>&1", cmd);

    // Use system() to run the command and check its return status
    int status = system(command);
    
    // If status is 0, the command exists; otherwise, it doesn't
    return (status == 0);
}
// Function to take input
int takeInput(char* str)
{
    char* buf;

    buf = readline(" ");
    if (strlen(buf) != 0) {
        add_history(buf);
        strcpy(str, buf);
        return 0;
    } else {
        return 1;
    }
}

// Function to print Current Directory.
void printDir()
{
    char cwd[1024];
    getcwd(cwd, sizeof(cwd));
    printf("\nDir: %s", cwd);
}

// Function where the system command is executed
void execArgs(char** parsed)
{
    // Forking a child
    pid_t pid = fork(); 

    if (pid == -1) {
        printf("\nFailed forking child..");
        return;
    } else if (pid == 0) {
        if (execvp(parsed[0], parsed) < 0) {
            printf("\nCould not execute command..");
        }
        exit(0);
    } else {
        // waiting for child to terminate
        wait(NULL); 
        return;
    }
}

// Function where the piped system commands is executed
void execArgsPiped(char** parsed, char** parsedpipe)
{
    // 0 is read end, 1 is write end
    int pipefd[2]; 
    pid_t p1, p2;

    if (pipe(pipefd) < 0) {
        printf("\nPipe could not be initialized");
        return;
    }
    p1 = fork();
    if (p1 < 0) {
        printf("\nCould not fork");
        return;
    }

    if (p1 == 0) {
        // Child 1 executing..
        // It only needs to write at the write end
        close(pipefd[0]);
        dup2(pipefd[1], STDOUT_FILENO);
        close(pipefd[1]);

        if (execvp(parsed[0], parsed) < 0) {
            printf("\nCould not execute command 1..");
            exit(0);
        }
    } else {
        // Parent executing
        p2 = fork();

        if (p2 < 0) {
            printf("\nCould not fork");
            return;
        }

        // Child 2 executing..
        // It only needs to read at the read end
        if (p2 == 0) {
            close(pipefd[1]);
            dup2(pipefd[0], STDIN_FILENO);
            close(pipefd[0]);
            if (execvp(parsedpipe[0], parsedpipe) < 0) {
                printf("\nCould not execute command 2..");
                exit(0);
            }
        } else {
            // parent executing, waiting for two children
            wait(NULL);
            wait(NULL);
        }
    }
}




void displayError() {
    printf("Unknown command. Type 'help' to see the list of commands.\n");
}


// Gryffindor Commands
void expelliarmus() {
    if(system("rm -rf ./corrupted_files") == 0){
        printf("Expelliarmus! Deleting corrupted files generated by Slytherin...\n");
    }
    else{
        printf("No corrupted files found.\n");
    }
    
}

void protego() {
    if(system("cp -r ./good_files/* ./backup_good_files") == 0){
        printf("Protego! Backing up good files...\n");
    }
    else{
        printf("No good files found.\n");
    }
  
}

void homenumRevelio() {
    DIR *dir = opendir("./hidden");  // Open directory
    
    if(dir && readdir(dir) != NULL){
        if(system("mv ./hidden/* ./main/") == 0){
            printf("Homenum Revelio! Moving hidden files to the main directory...\n");
        }
        else{
            printf("No hidden files found.\n");
        }
    }
    else{
        printf("No files found.\n");
    }
    closedir(dir);  // Close the directory
  
}

void displayHelp_Gryffindor(const char *command) {
    printf("\n***************************\n");
    printf("          GRYFFINDOR SHELL HELP MANUAL\n");
    printf("***************************\n");

    if (strcmp(command, "expelliarmus") == 0) {
        printf("\nCommand: expelliarmus\n");
        printf("Description: Remove corrupted files generated by other sources.\n");
        printf("Usage: Type 'expelliarmus' to scan and delete corrupted files in the current directory.\n");
    } else if (strcmp(command, "protego") == 0) {
        printf("\nCommand: protego\n");
        printf("Description: Create a backup of important files for safekeeping.\n");
        printf("Usage: Type 'protego to copy all critical files to the backup location.\n");
    } else if (strcmp(command, "homenum_revelio") == 0) {
        printf("\nCommand: homenum_revelio\n");
        printf("Description: Reveal and move hidden files to the main directory.\n");
        printf("Usage: Type 'homenum_revelio' to locate hidden files and move them to the current directory.\n");
    }
    else if (strcmp(command, "help") == 0) {
        printf("\nCommand: help\n");
        printf("Description: Display this manual or information about specific commands.\n");
        printf("Usage: Type 'help [command]' to get detailed information about a specific command.\n");
    } 
    else if (strcmp(command, "all") == 0) {
        printf("\nAvailable Commands:\n");
        printf("> expelliarmus     - Remove corrupted files generated by other sources.\n");
        printf("> protego          - Create a backup of important files for safekeeping.\n");
        printf("> homenum_revelio  - Reveal and move hidden files to the main directory.\n");
        printf("\nType 'help [command]' to get detailed information about a specific command.\n");
    } else {
        printf("\nError: Unknown command '%s'.\n", command);
        printf("Type 'help all' to view all available commands.\n");
    }

    printf("***************************\n");
}

int gryffindorShell(char** parsed) {


    if (strcmp(parsed[0], "expelliarmus") == 0) {
        expelliarmus();
        return 1;
    } 
    else if (strcmp(parsed[0], "protego") == 0) {
        protego();
        return 1;
    } 
    else if (strcmp(parsed[0], "homenumRevelio") == 0) {
        homenumRevelio();
        return 1;
    } 
    else if (strcmp(parsed[0], "help") == 0) {
        if (parsed[1] != NULL) {
            displayHelp_Gryffindor(parsed[1]);
        } else {
            displayHelp_Gryffindor("all");
        }
        return 1;
    } 
    else if (strcmp(parsed[0], "exit") == 0) {
        printf("Exiting Gryffindor shell. Goodbye!\n");
        exit(0);  // Terminate the program
    } 
    else {
        // Check if the command is a valid Linux command
        if (isLinuxCommand(parsed[0])) {
            execArgs(parsed);
            return 1; // Do nothing, let the shell handle it
        } else {
            displayError();
        }
    }
    return 0;
}

void createCorruptedFilesDirectory() {
    // Define the directory and file names
    char *dirName = "corrupted_files";
    char *fileName = "corrupted_files/temp_corrupt.txt";

    // Check if the directory exists
    struct stat st = {0};
    if (stat(dirName, &st) == -1) {
        // Directory does not exist, create it
        mkdir(dirName, 0700);
    }

    // Create the temp_corrupt.txt file inside the corrupted_files directory
    FILE *file = fopen(fileName, "w");
    if (file != NULL) {
        fclose(file);  // Close the file after creation
    }
}

// Slytherin Commands
void imperius() {
    if(system("echo '' > ./important.txt") == 0){
        printf("Imperius! Deleting contents or modifying files...\n");
    }
    else{
        printf("No important files found.\n");
    }
   
}

void serpensortia() {
    if(system("touch ./corrupted_files/file{1..5}.txt") == 0){
        printf("Serpensortia! Generating corrupted files...\n");
    }
    else{
        printf("No corrupted files found.\n");
    }
   
}

void obscuro() {
    DIR *dir = opendir("./main");
    if(dir && readdir(dir) != NULL){
        if(system("mv ./main/* ./hidden/") == 0){
            printf("Obscuro! Moving files to a hidden directory...\n");
        }
        else{
            printf("No files found in main directory.\n");
        }
    }
    else{
        printf("No files found.\n");
        return;
    }
    closedir(dir);
    
    
}
void displayHelp_Slytherin(const char *command) {
    printf("\n***********\n");
    printf("      SLYTHERIN SHELL MANUAL\n");
    printf("*********\n");

    if (strcmp(command, "imperius") == 0) {
        printf("\nCommand: imperius\n");
        printf("Description: Modify or delete sensitive files to suit your strategy.\n");
        printf("Usage: Type 'imperius' to modify or remove sensitive files in the current directory.\n");
    } else if (strcmp(command, "serpensortia") == 0) {
        printf("\nCommand: serpensortia\n");
        printf("Description: Generate corrupted files for testing purposes.\n");
        printf("Usage: Type 'serpensortia' to create random corrupted files for testing purposes.\n");
    } else if (strcmp(command, "obscuro") == 0) {
        printf("\nCommand: obscuro\n");
        printf("Description: Hide files by moving them to a hidden directory.\n");
        printf("Usage: Type 'obscuro' to hide files by relocating them to a hidden directory.\n");
    } else if (strcmp(command, "all") == 0) {
        printf("\nAvailable Commands:\n");
        printf("> imperius       - Modify or delete sensitive files to suit your strategy.\n");
        printf("> serpensortia   - Generate corrupted files for testing purposes.\n");
        printf("> obscuro        - Hide files by moving them to a hidden directory.\n");
        printf("\nType 'help [command]' to get detailed information about a specific command.\n");
    } else {
        printf("\nError: Unknown command '%s'.\n", command);
        printf("Type 'help all' to view all available commands.\n");
    }

    printf("*********\n");
}



int slytherinShell(char** parsed) {
    
    createCorruptedFilesDirectory();
    if (strcmp(parsed[0], "imperius") == 0){
        imperius();
        return 1;
    } 
    else if (strcmp(parsed[0], "serpensortia") == 0) {
        serpensortia();
        return 1;
    }
    else if (strcmp(parsed[0], "obscuro") == 0) {
        obscuro();
        return 1;
    }
    else if (strcmp(parsed[0], "help") == 0) {
        if (parsed[1] != NULL) {
            displayHelp_Slytherin(parsed[1]);
        } else {
            displayHelp_Slytherin("all");
        }
        return 1;
    } 
    else if (strcmp(parsed[0], "exit") == 0){
        printf("Exiting Slytherin shell. Goodbye!\n");
        exit(0);  // Terminate the program
    }
    else {
        // Check if the command is a valid Linux command
        if (isLinuxCommand(parsed[0])) {
            execArgs(parsed);
            return 1; // Do nothing, let the shell handle it
        } else {
            displayError();
        }
    }

    return 0;

}

// Hufflepuff Commands
void amortentia() {
    const char *dir_name = "./main";
    char file_name[50];
    FILE *file;

    // Create the directory if it doesn't exist
    // if (mkdir(dir_name, 0700) == -1 && errno != EEXIST) {
    //     perror("Error creating directory");
    //     return;
    // }

    // Seed the random number generator
    srand(time(NULL));

    // Generate a random file name (e.g., random_12345.txt)
    snprintf(file_name, sizeof(file_name), "%s/random_%d.txt", dir_name, rand());

    // Open the file for writing (create the file if it doesn't exist)
    file = fopen(file_name, "w");
    if (file == NULL) {
        perror("Error opening file");
        return;
    }
    // Write the message to the file
    fprintf(file, "New file created by hufflepuff\n");

    // Close the file
    fclose(file);
    
    printf("New text file generated by Hufflepuff.\n");
    
    
}

void patronus() {
    printf("Patronus! You are doing amazing. Keep up the great work!\n");
}

void prudens() {
    printf("Prudens! Here are some file management best practices:\n");
    printf("- Keep files organized by type.\n");
    printf("- Regularly back up important data.\n");
    printf("- Use meaningful file names.\n");
}

void displayHelp_Hufflepuff(const char *command) {
    printf("\n***********\n");
    printf("      HUFFLEPUFF SHELL MANUAL\n");
    printf("*********\n");

    if (strcmp(command, "amortentia") == 0) {
        printf("\nCommand: amortentia\n");
        printf("Description: Create a new text file.\n");
        printf("Usage: Type 'amortentia' to write a message to new text file.\n");
    } else if (strcmp(command, "patronus") == 0) {
        printf("\nCommand: patronus\n");
        printf("Description: Receive motivational messages to keep you going.\n");
        printf("Usage: Type 'patronus' to get an encouraging message to stay motivated.\n");
    } else if (strcmp(command, "prudens") == 0) {
        printf("\nCommand: prudens\n");
        printf("Description: Get practical tips for managing your files efficiently.\n");
        printf("Usage: Type 'prudens' to get helpful tips for better file organization and management.\n");
    } else if (strcmp(command, "all") == 0) {
        printf("\nAvailable Commands:\n");
        printf("> amortentia     - Creates a new text file with a message.\n");
        printf("> patronus       - Receive motivational messages to keep you going.\n");
        printf("> prudens        - Get practical tips for managing your files efficiently.\n");
        printf("\nType 'help [command]' to get detailed information about a specific command.\n");
    } else {
        printf("\nError: Unknown command '%s'.\n", command);
        printf("Type 'help all' to view all available commands.\n");
    }

    printf("*********\n");
}

int hufflepuffShell(char** parsed) {
    
   
    if (strcmp(parsed[0], "amortentia") == 0){
        amortentia();
        return 1;
    } 
    else if (strcmp(parsed[0], "patronus") == 0) {
        patronus();
        return 1;
    }
    else if (strcmp(parsed[0], "prudens") == 0) {
        prudens();
        return 1;
    }
    else if (strcmp(parsed[0], "help") == 0) {
        if (parsed[1] != NULL) {
            displayHelp_Hufflepuff(parsed[1]);
        } else {
            displayHelp_Hufflepuff("all");
        }
        return 1;
    } 
    else if (strcmp(parsed[0], "exit") == 0) {
        printf("Exiting Hufflepuff shell. Goodbye!\n");
        exit(0);  // Terminate the program
    }

    else {
        // Check if the command is a valid Linux command
        if (isLinuxCommand(parsed[0])) {
            execArgs(parsed);
            return 1; // Do nothing, let the shell handle it
        } else {
            displayError();
        }
    }
    
    return 0;
}




// Ravenclaw Commands
void ravenfacts() {
    const char *wisdoms[] = {
        "Wit beyond measure is man's greatest treasure.",
        "Logic will take you from A to B. Imagination will take you everywhere.",
        "The mind is not a vessel to be filled, but a fire to be kindled.",
        "Curiosity is the essence of intellect."
    };
    int numWisdoms = sizeof(wisdoms) / sizeof(wisdoms[0]);
    srand(time(0));
    printf("\nRavenclaw Wisdom: %s\n", wisdoms[rand() % numWisdoms]);
}

void quizme() {
    const char *riddles[] = {
        "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?",
        "The more of this you take, the more you leave behind. What is it?"
    };
    const char *answers[] = {"echo", "footsteps"};
    int numRiddles = sizeof(riddles) / sizeof(riddles[0]);

    srand(time(0));
    int index = rand() % numRiddles;

    char userAnswer[100];
    printf("\nRiddle: %s\nYour Answer: ", riddles[index]);
    fgets(userAnswer, sizeof(userAnswer), stdin);
    userAnswer[strcspn(userAnswer, "\n")] = 0; // Remove trailing newline

    if (strcmp(userAnswer, answers[index]) == 0) {
        printf("\nCorrect! Ravenclaw-worthy intellect!\n");
    } else {
        printf("\nIncorrect. The correct answer is: %s\n", answers[index]);
    }
}

void findHorcrux() {
    printf("Finding horcrux...\n");
    if(system("find . -name 'horcrux.txt' > horcrux_location.txt") == 0){
        
        printf("Search complete! Check horcrux_location.txt for results.\n");

    }
    else{
        printf("No horcrux found.\n");
    }
}

void displayHelp_Ravenclaw(const char *command) {
    printf("\n***********\n");
    printf("      RAVENCLAW SHELL MANUAL\n");
    printf("*********\n");

    if (strcmp(command, "ravenfacts") == 0) {
        printf("\nCommand: ravenfacts\n");
        printf("Description: Receive a random quote of wisdom.\n");
        printf("Usage: Type 'ravenfacts' to get a random quote from the Ravenclaw library of wisdom.\n");
    } else if (strcmp(command, "quizme") == 0) {
        printf("\nCommand: quizme\n");
        printf("Description: Test your intellect with a Ravenclaw riddle.\n");
        printf("Usage: Type 'quizme' to challenge yourself with a riddle.\n");
    } else if (strcmp(command, "findhorcrux") == 0) {
        printf("\nCommand: findhorcrux\n");
        printf("Description: Locate the elusive 'horcrux.txt' in your directories.\n");
        printf("Usage: Type 'findhorcrux' to search your directories for the hidden 'horcrux.txt'.\n");
    } else if (strcmp(command, "help") == 0) {
        printf("\nCommand: help\n");
        printf("Description: Display this manual or information about specific commands.\n");
        printf("Usage: Type 'help [command]' to get detailed information about a specific command.\n");
    } else if (strcmp(command, "all") == 0) {
        printf("\nAvailable Commands:\n");
        printf("> ravenfacts    - Receive a random quote of wisdom.\n");
        printf("> quizme        - Test your intellect with a Ravenclaw riddle.\n");
        printf("> findhorcrux   - Locate the elusive 'horcrux.txt' in your directories.\n");
        printf("> help          - Display this manual or information about specific commands.\n");
        printf("\nType 'help [command]' to get detailed information about a specific command.\n");
    } else {
        printf("\nError: Unknown command '%s'.\n", command);
        printf("Type 'help all' to view all available commands.\n");
    }

    printf("*********\n");
}


int ravenclawShell(char** parsed) {
    
    
    if (strcmp(parsed[0], "ravenfacts") == 0){
        ravenfacts();
        return 1;
    }
    else if (strcmp(parsed[0], "quizme") == 0) {
        quizme();
        return 1;
    }
    else if (strcmp(parsed[0], "findHorcrux") == 0) {
        findHorcrux();
        return 1;
    }

    else if (strcmp(parsed[0], "help") == 0) {
        if (parsed[1] != NULL) {
            displayHelp_Ravenclaw(parsed[1]);
        } else {
            displayHelp_Ravenclaw("all");
        }
        return 1;
    } 
    else if (strcmp(parsed[0], "exit") == 0){
        printf("Exiting RavenClaw shell. Goodbye!\n");
        exit(0);  // Terminate the program
    }
    else {
        // Check if the command is a valid Linux command
        if (isLinuxCommand(parsed[0])) {
            execArgs(parsed);
            return 1; // Do nothing, let the shell handle it
        } else {
            displayError();
        }
    }
    return 0;
}


// function for finding pipe
int parsePipe(char* str, char** strpiped)
{
    int i;
    for (i = 0; i < 2; i++) {
        strpiped[i] = strsep(&str, "|");
        if (strpiped[i] == NULL)
            break;
    }

    if (strpiped[1] == NULL)
        return 0; // returns zero if no pipe is found.
    else {
        return 1;
    }
}

// function for parsing command words
void parseSpace(char* str, char** parsed)
{
    int i;

    for (i = 0; i < MAXLIST; i++) {
        parsed[i] = strsep(&str, " ");

        if (parsed[i] == NULL)
            break;
        if (strlen(parsed[i]) == 0)
            i--;
    }
}

int processString(char* str, char** parsed, char** parsedpipe, int house)
{

    char* strpiped[2];
    int piped = 0;

    piped = parsePipe(str, strpiped);

    if (piped) {
        parseSpace(strpiped[0], parsed);
        parseSpace(strpiped[1], parsedpipe);

    } else {

        parseSpace(str, parsed);
    }

    if (house == 0){
        if(gryffindorShell(parsed)){
            return 0;
        }
        else{
            return 1 + piped;
        }
    }
    else if (house == 1){
        if(slytherinShell(parsed)){
            return 0;
        }
        else{
            return 1 + piped;
        }
    }
    else if (house == 2){
        if(hufflepuffShell(parsed)){
            return 0;
        }
        else{
            return 1 + piped;
        }
    }
    else{
        if(ravenclawShell(parsed)){
            return 0;
        }
        else{
            return 1 + piped;
        }
    }
}

int shell_cmds(int house){
    char command[50];
    char inputString[MAXCOM], *parsedArgs[MAXLIST];
    char* parsedArgsPiped[MAXLIST];
    int execFlag = 0;
    if (house == 0){
            printf("\nWelcome to the Gryffindor Terminal!\n");
            printf("Commands: expelliarmus, protego, homenumRevelio, help, exit\n");
        }
        else if (house == 1){
            printf("\nWelcome to the Slytherin Terminal!\n");
            printf("Commands: imperius, serpensortia, obscuro, help, exit\n");
        }
        else if (house == 2){
            printf("\nWelcome to the Hufflepuff Terminal!\n");
            printf("Commands: amortentia, patronus, prudens, help, exit\n");
        }
        else{
            printf("\nWelcome to the RavenClaw Terminal!\n");
            printf("Commands: ravenfacts, quizme, findHorcrux, help, exit\n");
        }

    while (1) {
        // print shell line
        if (house == 0){
            printf("Gryffindor> ");
        }
        else if (house == 1){
            printf("Slytherin> ");
        }
        else if (house == 2){
            printf("Hufflepuff> ");
        }
        else{
            printf("Ravenclaw> ");
        }
        

        
        // take input
        if (takeInput(inputString))
            continue;
        // process
        execFlag = processString(inputString,
        parsedArgs, parsedArgsPiped, house);
        // execflag returns zero if there is no command
        // or it is a builtin command,
        // 1 if it is a simple command
        // 2 if it is including a pipe.

        // execute
        if (execFlag == 1)
            execArgs(parsedArgs);

        if (execFlag == 2)
            execArgsPiped(parsedArgs, parsedArgsPiped);
    }
}
const char* sortingHat() {
    int gryffindor = 0, hufflepuff = 0, ravenclaw = 0, slytherin = 0;
    char answer[10];

    printf("\nWelcome to the Sorting Hat Ceremony!\n");
    printf("Answer the following questions with 'yes' or 'no'.\n");

    // Questions
    printf("\nQ1: Do you enjoy taking risks and facing challenges? (yes/no): ");
    fgets(answer, sizeof(answer), stdin);
    if (strcmp(answer, "yes\n") == 0) gryffindor++;

    printf("\nQ2: Do you value intelligence and creative thinking above all? (yes/no): ");
    fgets(answer, sizeof(answer), stdin);
    if (strcmp(answer, "yes\n") == 0) ravenclaw++;

    printf("\nQ3: Are you loyal and hardworking, always ready to help others? (yes/no): ");
    fgets(answer, sizeof(answer), stdin);
    if (strcmp(answer, "yes\n") == 0) hufflepuff++;

    printf("\nQ4: Do you aspire to be a leader and achieve great success, no matter the cost? (yes/no): ");
    fgets(answer, sizeof(answer), stdin);
    if (strcmp(answer, "yes\n") == 0) slytherin++;

    // Determine house
    int maxScore = gryffindor;
    const char *house = "Gryffindor";
    if (hufflepuff > maxScore) { maxScore = hufflepuff; house = "Hufflepuff"; }
    if (ravenclaw > maxScore) { maxScore = ravenclaw; house = "Ravenclaw"; }
    if (slytherin > maxScore) { maxScore = slytherin; house = "Slytherin"; }

    printf("\nCongratulations! You have been sorted into %s!\n", house);


    return house;
}


void displayHogwarts(){
    printf("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
    printf("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
    printf("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠀⠀⠀⠀⠀⣼⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
    printf("⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠠⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
    printf("⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣇⠀⠀⠀⣷⠈⣿⣿⡇⢠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
    printf("⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⠀⠀⢨⣿⡀⣿⣿⡇⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
    printf("⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⡆⠀⢸⣿⣇⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
    printf("⠀⢠⠀⠀⠀⠀⠀⠀⣿⣿⣿⠁⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀\n");
    printf("⠀⣾⡄⠀⠀⠀⠀⠀⣿⣿⣿⡆⠀⢸⣿⣿⣿⣿⣿⣿⡇⠀⢀⣦⠀⠀⠀⠀⠀⠀\n");
    printf("⢰⣿⡇⢰⡆⠀⢀⣀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣾⣾⣿⠀⠀⠀⠰⠆⠀\n");
    printf("⣸⡿⣇⣸⣟⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀\n");
    printf("⢻⣿⣿⣿⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁⠀⢠⣾⣄⠀\n");
    printf("⢸⣿⣿⣿⣿⢸⣏⣿⣹⣏⣿⣹⣏⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀⣿⣿⣿⠂\n");
    printf("⢸⣿⣿⣿⣿⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⣿⣿⣿⣷\n");
    printf("⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠁\n");
    printf("⠈⠉⠉⠉⠉⠉⠉⣉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠀\n");
    printf("⠀⠀⠀⠀⠀⢸⡇⣿⣀⡠⡀⣴⢲⢀⡄⡀⡄⠖⣦⢸⠒⣾⠂⣠⡀⠀⠀⠀⠀⠀\n");
    printf("⠀⠀⠀⠀⠀⢺⡗⣿⠸⡇⡇⠧⢸⠘⣧⢇⠇⠻⠿⠸⠀⣿⢀⣳⡅⠀⠀⠀⠀⠀\n");
    printf("⠀⠀⠀⠀⠀⠘⠃⠿⠀⠀⠀⣄⠜⠀⠀⠀⠀⠀⠀⠀⠀⠉⠀⠁⠀⠀⠀⠀⠀⠀\n");
  


}

void createBackupDirectory() {
    // Define the directory name
    char *dirName = "backup_good_files";

    // Check if the directory exists
    struct stat st = {0};
    if (stat(dirName, &st) == -1) {
        // Directory does not exist, create it
        mkdir(dirName, 0700);
    }
}

void createGoodFilesDirectory() {
    // Define the directory and file names
    char *dirName = "good_files";
    char *fileName = "good_files/harry.txt";

    // Check if the directory exists
    struct stat st = {0};
    if (stat(dirName, &st) == -1) {
        // Directory does not exist, create it
        mkdir(dirName, 0700);
    }

    // Create the harry.txt file inside the good_files directory
    FILE *file = fopen(fileName, "w");
    if (file != NULL) {
        fclose(file);  // Close the file after creation
    }
}

void createHiddenFilesDirectory() {
    // Define the directory and file names
    char *dirName = "hidden";
    char *fileName = "hidden/temp_hidden.txt";

    // Check if the directory exists
    struct stat st = {0};
    if (stat(dirName, &st) == -1) {
        // Directory does not exist, create it
        mkdir(dirName, 0700);
    }

    // Create the temp_hidden.txt file inside the hidden directory
    FILE *file = fopen(fileName, "w");
    if (file != NULL) {
        fclose(file);  // Close the file after creation
    }
}

void createMainDirectory() {
    // Define the directory and file names
    char *dirName = "main";
    char *fileName = "main/temp_main.txt";

    // Check if the directory exists
    struct stat st = {0};
    if (stat(dirName, &st) == -1) {
        // Directory does not exist, create it
        mkdir(dirName, 0700);
    }

    // Create the temp_main.txt file inside the main directory
    FILE *file = fopen(fileName, "w");
    if (file != NULL) {
        fclose(file);  // Close the file after creation
    }
}

void createHorcruxLocationFile() {
    // Define the file name
    char *fileName1 = "horcrux_location.txt";
    char *fileName2 = "horcrux.txt";

    // Create the horcrux_location.txt file
    FILE *file1 = fopen(fileName1, "w");
    if (file1 != NULL) {
        fclose(file1);  // Close the file after creation
    }
    FILE *file2 = fopen(fileName2, "w");
    if (file2 != NULL) {
        fclose(file2);  // Close the file after creation
    }
}

void createFiles(){
    createBackupDirectory();
    createCorruptedFilesDirectory();
    createGoodFilesDirectory();
    createHiddenFilesDirectory();
    createMainDirectory();
    createHorcruxLocationFile();

}

int main()
{
    init_shell();
    displayHogwarts();
    
    createFiles();
    
    const char* house = sortingHat();

    if (strcmp(house, "Gryffindor") == 0) shell_cmds(0);
    else if (strcmp(house, "Slytherin") == 0) shell_cmds(1);
    else if (strcmp(house, "Hufflepuff") == 0) shell_cmds(2);
    else if (strcmp(house, "Ravenclaw") == 0) shell_cmds(3);

  
    
   
    return 0;
}